### ISSUE TITLE
How to invoke code before RTIC main part.

### ISSUE THREAD

**Issue by kareled** [rtic-rs/rtic#909]
Hello,
while developing firmware code using RTIC we got to the need to invoke STM32 system firmware to support our firmware update. Jumping to STM32 F4(12) system firmware (also boot) form the application code is pretty simple:
```
fn main() -> ! {
    let SYSBOOT_ADDR : u32 = 0x1FFF0000;
    let vt = SYSBOOT_ADDR as *const u32;

    unsafe {
        (*STK::ptr()).ctrl.modify(|_, w| w.bits(0x0));
        (*STK::ptr()).load.modify(|_, w| w.bits(0x0));
        (*STK::ptr()).val.modify(|_, w| w.bits(0x0));

        // sysflash remap to 0x0 addr
        (*SYSCFG::ptr()).memrm.modify(|_, w| w.mem_mode().bits(0x1));

        let mut periph = cortex_m::peripheral::Peripherals::steal();
        periph.SCB.vtor.write(vt as u32);
        periph.SCB.invalidate_icache();
        cortex_m::asm::bootload(vt);
    }
    loop {
    }
}

```
however the process is complicated when there was some hardware already initialized and set. This needs to be reset into its default state. This itself is quite hard to do and so far impossible for me to the with RTIC application. What may simplify things is if there would be some way how to invoke application code even before main RTIC code. Some kind of main_start_interceptor function or so. There user may put his/her bare-metal rust code to do init business (or jump to system firmware) once the conditions are met (like for example button is hold down during the startup).
Obviously: the issue is that main is machine generated into the rtic-extension.rs and it's a bit harder to modify correctly....

**Comment by AfoHT** [comment]
Hi!

Did you try `[pre-init]`?

https://rtic.rs/2/book/en/by-example/app_init.html?highlight=pre-init#app-initialization-and-the-init-task

which in turn links to https://docs.rs/cortex-m-rt/latest/cortex_m_rt/attr.pre_init.html

Another approach, if always going through a bootloader, by doing an actual reset to ensure you get all peripherals into a known state.

After the reset, depending on some leftover state/GPIO state as already mentioned maybe then jump into the system firmware updater application instead of the regular application.

Many ways to go about it, but on the direct question "how to invoke code before RTIC main part" I would reply `[pre-init]` :)     
I will close the issue, but feel free to reopen/discuss further!
